### ISSUE TITLE
Add a promo sidebar in the Free version

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Planner#1203]
Let's use the style we have in Authors, Series, and more:
![Screen Shot 2022-12-01 at 11 32 39 AM](https://user-images.githubusercontent.com/3868028/205107942-8088d5da-f715-41d1-aafe-b386b58f3112.png)

**Comment by olatechpro** [comment]
@stevejburge I didn't see any pages with spaces where this will fit in.

Can you confirm if you have some free pages you think this can be?

**Comment by olatechpro** [comment]
@stevejburge What should be the promo texts?

**Comment by stevejburge** [comment]
@olatechpro Let's copy the Authors sidebar for the main text

For the bullet items, let's use these: https://publishpress.com/knowledge-base/publishpress-free-pro/

Slack integration for notifications 
Send reminder notifications
Use post meta in notifications
Remove PublishPress ads and branding
Fast, professional support
