### ISSUE TITLE
Query Monitor PHP deprecated on Planner

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Planner#1223]
> Pimple\Container::offsetExists($id) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/public/wp-content/plugins/publishpress-pro/lib/wppf2/vendor/pimple/pimple/src/Pimple/Container.php on line 133
> 
> Deprecated: Return type of Pimple\Container::offsetGet($id) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/public/wp-content/plugins/publishpress-pro/lib/wppf2/vendor/pimple/pimple/src/Pimple/Container.php on line 98
> 
> Deprecated: Return type of Pimple\Container::offsetSet($id, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/public/wp-content/plugins/publishpress-pro/lib/wppf2/vendor/pimple/pimple/src/Pimple/Container.php on line 79
> 
> Deprecated: Return type of Pimple\Container::offsetUnset($id) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/public/wp-content/plugins/publishpress-pro/lib/wppf2/vendor/pimple/pimple/src/Pimple/Container.php on line 143

**Comment by stephenheron** [comment]
Just to give someone a head start on this, Pimple version 3.5 has support for PHP 8.1 which is where this issue crops up. 

https://github.com/silexphp/Pimple/blob/main/CHANGELOG

**Comment by olatechpro** [comment]
Fixed in the last release
