### ISSUE TITLE
Shortcode meta date is not showing

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Planner#1230]
ISSUE: Shortcode [psppno_post meta-date] is not showing on the notification

![image](https://user-images.githubusercontent.com/83811723/210349453-9b33bb8a-0f9d-4005-8608-fcce1d5d5369.png)

Ticket: https://secure.helpscout.net/conversation/2113309114/174176?folderId=6932143

**Comment by olatechpro** [comment]
@rizaardiyanto1412 the problem seems to be from the documentation https://publishpress.com/knowledge-base/customize-email-notifications/

The right shortcode is **[psppno_post date]** as date is not a meta.
