### ISSUE TITLE
Content Overview dates filter reset not working

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Planner#1378]
> The filters do reset, but not the date range. It took me awhile to figure out why my content was not showing up. So i had to manually change the dates to include the current week.

![331886927_2118421915212369_4780115706333964338_n](https://user-images.githubusercontent.com/3868028/219707562-60344b3e-577d-4d8b-b7c0-0d2f37041d6b.jpg)

**Comment by ronyedin** [comment]
Ideally, date range should include the current week be default at all times unless you manually change the date range in my opinion. This might be the only setting that it should not remember because content changes daily as new posts come in.
