### ISSUE TITLE
Deprecations notice on PHP 8.1

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Planner#1414]
![Screenshot 2023-06-19 at 12 41 11 PM](https://github.com/publishpress/PublishPress-Planner/assets/3868028/cb99681e-e3e4-4721-8d72-753e765ade97)

**Comment by rizaardiyanto1412** [comment]
Another warning raised by another customer:

[Tue Jun 27 14:20:01.176529 2023] [proxy_fcgi:error] [pid 12197] [client 192.168.75.105:51763] AH01071: Got error 'PHP message: PHP Warning: Array to string conversion in /var/www/sasis/htdocs/wp-content/plugins/publishpress/lib/Notifications/Workflow/Step/Channel/Email.php on line 214', referer: https://www.sasis.local/wp-admin/post-new.php

**Comment by olatechpro** [comment]
@rizaardiyanto1412 I'm moving your comment report to another issue as I'm not able to replicate yet or understand the condition where the error is happening.

https://github.com/publishpress/PublishPress-Planner/issues/1442
