### ISSUE TITLE
Remove the Dashboard Widgets

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Planner#1449]
There are some dashboard widgets in Planner that are in an odd situation.
 
Can we remove them, or perhaps replace them with views such as the "Content Calendar" or "Content Overview"

The widgets currently exist:
<img width="511" alt="Screenshot 2023-09-05 at 3 21 22 PM" src="https://github.com/publishpress/PublishPress-Planner/assets/3868028/d5122cf2-7612-4343-b969-f1375f354259">

But they can't be turned off:
<img width="442" alt="Screenshot 2023-09-05 at 3 21 50 PM" src="https://github.com/publishpress/PublishPress-Planner/assets/3868028/de48a7df-48b5-4623-8c87-6671432465b6">

**Comment by stevejburge** [comment]
We've had one request that's similar to "Content Overview". A user wanted to be able to sort posts according to their status:
![Screenshot 2023-09-05 at 3 23 29 PM](https://github.com/publishpress/PublishPress-Planner/assets/3868028/54c63f4a-7118-4ddd-a789-2deabe593697)

Sample code:

[display-pending-posts.zip](https://github.com/publishpress/PublishPress-Planner/files/12527647/display-pending-posts.zip)

**Comment by olatechpro** [comment]
@stevejburge Is this comment related to the issue?

**Comment by stevejburge** [comment]
@olatechpro Yes, it was one customer suggestion. They wanted a more flexible dashbard widget, similar to that plugin, or our Content Overview

**Comment by olatechpro** [comment]
To be sincere, I still don't understand what you want me to do very well.

From the description:
> Can we remove them, or perhaps replace them with views such as the "Content Calendar" or "Content Overview"

To this @stevejburge

**Comment by stevejburge** [comment]
@olatechpro Fair point.

I guess let's start with this ... is it better fix these widgets, or just remove them? Right now they are not very useful.

**Comment by stevejburge** [comment]
@olatechpro OK, agreed. We've more important tasks. Let's remove

**Comment by ckoerner** [comment]
Hello, I'm a user of this wonderful plugin and I noticed that the "Unpublished Content" widget is no longer available. I help run a community blog that sees quite a few submissions every week. This widget was a helpful way to see what was in our queue and act accordingly. I'd like to kindly encourage you to keep it around, perhaps as an option?

**Comment by rizaardiyanto1412** [comment]
Another use also using it regularly: https://github.com/publishpress/PublishPress-Planner/issues/1449

Maybe worth to add it as an option @olatechpro @stevejburge ?

**Comment by stevejburge** [comment]
@ckoerner @olatechpro Perhaps we return that one dashboard widget in the next release, while we work on better options?

**Comment by Janoubie** [comment]
I'm a fan of PublishPress & I just registered to github to till you that I rolled back to 3.12.1 because of "Unpublished Contents" dashboard widget removal!
Those small links are very important for the Editors to go directly for Pitch, Assigned, Draft, Pending, etc posts by clicking the hyperlinked type.
"Unpublished Contents" should be back asap, please!
