### ISSUE TITLE
Statuses to display publish time

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Planner#1504]
This setting is broken in Safari

![Screenshot 2023-12-14 at 11 23 13 AM](https://github.com/publishpress/PublishPress-Planner/assets/3868028/87189af2-f06e-4d27-91d2-46b3c5a84f1b)

**Comment by olatechpro** [comment]
For some reason, this is not broken in my safari

<img width="1440" alt="Screenshot 2023-12-20 at 6 01 17 AM" src="https://github.com/publishpress/PublishPress-Planner/assets/46832636/e02d9f0e-c608-4018-8f15-e61b98184c1b">

**Comment by olatechpro** [comment]
For some reason, this is not broken in my safari

<img width="1440" alt="Screenshot 2023-12-20 at 6 01 17 AM" src="https://github.com/publishpress/PublishPress-Planner/assets/46832636/e02d9f0e-c608-4018-8f15-e61b98184c1b">
@stevejburge

**Comment by stevejburge** [comment]
@olatechpro In the latest release this does appear fixed in Safari.
