### ISSUE TITLE
Fatal error after deactivating Pro and activating the Free, still on the plugins screen

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Planner#1510]
It happens after module `custom_status` is loaded.

>Fatal error: Uncaught Error: Call to undefined method PP_Module::init()
in /www/kinsta/public/php80dev/wp-content/plugins/publishpress/publishpress.php on line 239

![image](https://github.com/publishpress/PublishPress-Planner/assets/407131/f48fa6f2-79b4-4e00-b073-a76e3568cedf)

Module custom status is not available anymore. But beside of that, we probably need to guarantee that initialization routine do not break if the module class do not have a init method.

**Comment by andergmartins** [comment]
After testing more, I realise that is happening because my IDE updated the plugin folder in my test site without completely removing the old folder. So on my site we still have a `custom_status` folder in the modules dir. That will probably not be a problem for new users, or users that update using WP UI. But if the user updates merging the new folder into the old one, we might see the issue.

That happens because the plugin look for the modules in the folders found, instead of hard-coded list of codes (which would probably be faster to execute).

**Comment by olatechpro** [comment]
@andergmartins I'm not able to replicate this even after copying `custom_status` folder to the modules dir.

If you can attach the version with the problem, I'll be able to test and fix for the possibility
