### ISSUE TITLE
Update to Planner 4.0.2 -- statuses have disappeared from post edit

### ISSUE THREAD

**Issue by poindexter47** [publishpress/PublishPress-Planner#1526]
The only remaining status selectors are "Draft" and "Pending Review". Before the update we also had "assigned", "draft complete", "in progress", "pitch", and "approved" selectors. Is this related to the new PublishPress Status plugin release?

Thanks!

**Comment by poindexter47** [comment]
<img width="419" alt="Screenshot 2024-01-07 at 1 53 36 PM" src="https://github.com/publishpress/PublishPress-Planner/assets/128197079/9b35c4af-239c-4a6a-9ed8-e17585a3b2a8">

**Comment by stevejburge** [comment]
@poindexter47 Thanks for reporting this, but Github is for reporting bugs, not support about your site.

Can you open a Pro member support ticket, or use our Free support: https://wordpress.org/support/plugin/publishpress-statuses/
