### ISSUE TITLE
Stop Notifying Me link does not work

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Planner#1539]
The link Stop Notifying Me (in the post overview table) is not working.
![image](https://github.com/publishpress/PublishPress-Planner/assets/83811723/c1a92d6c-f6b2-40f1-a337-163ca12bd2e6)

I have this issue on three websites on three different servers, with plugin version 4.0.2 as well as 3.12.2.

Disabling all other plugins gave the same result. I don’t know if it was working before because I never used it before. The Notify Me link does work btw.

Any help is welcome! Thank you!

Original report: https://wordpress.org/support/topic/stop-notifying-me-link-does-not-work/

**Comment by olatechpro** [comment]
@rizaardiyanto1412 Can you confirm if user doesn't belong to any of other options selected in the Roles, Users etc?

Notify me/stop notifying me is only for `"Users who selected "Notify me"` for the content" option and not global.

![n](https://github.com/publishpress/PublishPress-Planner/assets/46832636/88b0ddaf-6fb4-477e-9887-1a2ad9ab3a08)

**Comment by rizaardiyanto1412** [comment]
@olatechpro It seems you are correct. Thanks,
