### ISSUE TITLE
Add a search box to the Calendar

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Planner#1560]
As we match up the filters between the Calendar and Content Overview, can we add a search box to the Calendar?
![Screenshot 2024-02-13 at 11 37 23 AM](https://github.com/publishpress/PublishPress-Planner/assets/3868028/c66584d9-76db-44a8-83c4-2cfbfd79cf4f)

**Comment by olatechpro** [comment]
Related to https://github.com/publishpress/PublishPress-Planner/issues/1603
