### ISSUE TITLE
Content Calendar not displaying on Old WordPress Version

### ISSUE THREAD

**Issue by olatechpro** [publishpress/PublishPress-Planner#1588]
On a website running wordpress v5.8.9, content calendar is showing blank page with the error below in console log

![image (2)](https://github.com/publishpress/PublishPress-Planner/assets/46832636/0eda700b-fc28-4a2e-89ca-c0e2538a8855)

**Comment by gabriella-aguilar** [comment]
@olatechpro I'm supporting on a site using Word Press 6.1.4 and am encountering the same issue. Is there any projected timeline on when this fix will be released?
