### ISSUE TITLE
Disable Editorial Comments and Fields for new sites

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Planner#1600]
I've been reading through the details of what is planned for Gutenberg Phase 3 and am sure some kind of comments are coming.

I think we should disable the "Editorial Comments" feature for new sites. Fields should go as well, as it's a minor feature and done much better in other plugins.

**Comment by stevejburge** [comment]
If we do this, we'll also need to replace this Notification. Details here https://github.com/publishpress/PublishPress-Planner/issues/1601

![Screenshot 2024-04-29 at 12 06 21 PM](https://github.com/publishpress/PublishPress-Planner/assets/3868028/5d567515-705c-4b61-83c5-d353adabceb4)

**Comment by stevejburge** [comment]
Postponing this for now until comments are in the WP core

**Comment by olatechpro** [comment]
Removing this from 4.3.1
