### ISSUE TITLE
Remove "Make Viewable"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Planner#1636]
I think this feature is now useless?
![Screenshot 2024-05-16 at 3 28 12 PM](https://github.com/publishpress/PublishPress-Planner/assets/3868028/0495d2f6-2a0d-498e-9210-6c148860742a)

**Comment by stevejburge** [comment]
@olatechpro OK, good point. Let's fix that when we update this https://github.com/publishpress/PublishPress-Planner/issues/1635

**Comment by olatechpro** [comment]
Moving this to same milestone as https://github.com/publishpress/PublishPress-Planner/issues/1687.

The issue will be fixed when we replace the modal according to requirement as it's been used in modal
