### ISSUE TITLE
Move the remaining planner capabilities to correct tab in the Capabilities plugin

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Planner#1638]
This doesn't need to be called 'edit metadata' any more. It can be "edit editorial fields"

We also seem to have a "view editorial metadata" permissions that is no longer in Capabilities

![capabilities-fields](https://github.com/publishpress/PublishPress-Planner/assets/3868028/afcb4bda-c363-4520-8f10-250bf8bdb319)

**Comment by stevejburge** [comment]
@olatechpro OK, let's keep it. Let's just make sure all the Planner capabilities are under the "Planner" tab please

**Comment by olatechpro** [comment]
@stevejburge Does this issue still exist in the last released version as I noticed you reopened it after the release?

**Comment by stevejburge** [comment]
I think we're just missing 3, around notification workflows
![Screenshot 2024-07-16 at 10 26 15 AM](https://github.com/user-attachments/assets/f44d2b0a-fb8b-4a74-8451-1c02410fbbe1)
