### ISSUE TITLE
Adjust default colors of core statuses to match Statuses plugin

### ISSUE THREAD

**Issue by agapetry** [publishpress/PublishPress-Planner#1670]
Per conversation with @stevejburge, please adjust status colors to match the Statuses plugin's default values:

https://github.com/publishpress/PublishPress-Statuses/blob/88fda6fd635700e45bdf6d891a9704eb91bfa5b1/PublishPress_Statuses.php#L576

This pertains only to core statuses defined by WordPress (Draft, Pending, Scheduled, Published, Private).

**Comment by olatechpro** [comment]
Getting color from https://github.com/publishpress/PublishPress-Statuses/blob/main/PublishPress_Statuses.php#L561
