### ISSUE TITLE
Notification is not triggered from Future Action

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Planner#1675]
Step to replicate:
1. Create new post
2. Enable future action
3. You could add action like adding categories or else
![image](https://github.com/user-attachments/assets/c0422ea5-f68e-434b-b8f3-a4d79001a0ed)

5. Publish
6. Enable notification with this setting:

![image](https://github.com/user-attachments/assets/114536d1-f2cd-471c-8cb4-10d0c0858fe3)

Expected behavior, notification is triggered with future action being fired

Original report: https://wordpress.org/support/topic/notification-isnt-triggered-when-pp-future-updates-post/

This is happens because Notification "When content is update" relied on save_post which Future action does not trigger

**Comment by andergmartins** [comment]
Hey guys, I agree with Ola. It will make it clear if we have another specific option for taxonomy changes, instead of catching that in the current "When content is updated" trigger.

This is something we also should cover on the Actions Workflow: https://github.com/publishpress/PublishPress-Future/issues/931

**Comment by andergmartins** [comment]
I'm also not fully sure about the side effects (for 3rd party plugins, for example) of enforcing to fire `save_post` hook when taxonomy has changed for the post. I would take the simplest path for now, adding a new option to that box, as suggested above.

**Comment by rizaardiyanto1412** [comment]
Duly noted. Thanks for your feedback @andergmartins 

Should I close this one and create new issue @olatechpro ? Or we could make that happen on this issue, just need to update it?

**Comment by olatechpro** [comment]
@rizaardiyanto1412 Just rename the issue title to reflect new focus

**Comment by olatechpro** [comment]
@rizaardiyanto1412 Never mind on renaming this topic, I've added the issue in https://github.com/publishpress/PublishPress-Planner/issues/1759

**Comment by rizaardiyanto1412** [comment]
Thanks @olatechpro
