### ISSUE TITLE
Add modal to Content Calendar and Content Overview screens

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Planner#1687]
Can we use the modal on the Content Calendar and Content Overview screens?

**Comment by olatechpro** [comment]
@stevejburge  Content Calendar own is going to be difficult due to the calendar been reactjs and also, it has it own modal, it's possible though but will take time as it's impossible to copy Content Board code(php) but instead, will need to implement it for react separately in reactjs.

**Comment by stevejburge** [comment]
OK, let’s move that to the next milestone

**Comment by olatechpro** [comment]
It's actually already in the next milestone but I'm dropping it here for then and also this too so it can be clarified.
For example, we already has a modal in Calendar.

So, that shows the existing simple modal should be removed too? @stevejburge 

![cal](https://github.com/user-attachments/assets/83cbb7ed-8e02-4f4c-bc8f-38f467a72bf1)

**Comment by stevejburge** [comment]
Yes, let’s use the better, new modal

**Comment by olatechpro** [comment]
Got it now @stevejburge

**Comment by stevejburge** [comment]
@olatechpro Is it possible to leave the old modal in place for free users?
