### ISSUE TITLE
Calendar not loading older post on navigation

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Planner#1707]
To replicate:

Go to the content calendar. (looks fine)
Click << or < to go back a month or week.
Issue: No posts show in the previous month or week (we have 3 plus posts per day that should be displaying)

Original report: https://wordpress.org/support/topic/content-calendar-not-functioning-as-expected-since-update/

Personally I could confirm this

**Comment by stevejburge** [comment]
Also reported here: https://secure.helpscout.net/conversation/2660258727/224489?folderId=2557458
