### ISSUE TITLE
Add settings to control the maximum number of posts on Content Overview and Board page

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Planner#1772]
This seems like a good idea from a customer: 

"Content Overview seems to be limited to 200 items. Is this correct? or a preference I can't find?"

They would like this limit to be customizable. Maybe we can add the setting to the other screens too

**Comment by olatechpro** [comment]
@stevejburge Should we add this to the settings page or simply add a Settings button to the filter row on each screen with a pop that include this setting for a start?

**Comment by stevejburge** [comment]
Thanks @olatechpro. Can we add it as a filter?

**Comment by olatechpro** [comment]
Okay

**Comment by olatechpro** [comment]
This should be implemented alongside pagination mentioned here https://github.com/publishpress/PublishPress-Planner/issues/1610 but since we're not coming back to Planner for awhile and result limits is already in request, I'll simply do that and pagination can come in next time we work on this
