### ISSUE TITLE
Show and Add metadata on the Calendar

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Planner#284]
At least 2 requests for this so far.

Here's one customer:

> add meta data (due date, assignment details) from the calendar – have to go to the post itself

From https://github.com/publishpress/PublishPress/issues/664

> We need a new field in the metadata field to say if it can be added in the calendar. If so, we should display the metadata fields in the pop-up used to create posts in the calendar.

**Comment by stevejburge** [comment]
> Is there a way to get the First Draft Date to show up on the PublishPress calendar? The blogs show up based on the Publish date, which seems to be the date they were entered into the system (all in the past).

**Comment by stevejburge** [comment]
> What would be great is to be able to add the metadata fields to the content creation forms in the calendar view, or just have a separate field for submission or first draft deadline/date that is editable from the content creation forms in the calendar view.

**Comment by olatechpro** [comment]
@stevejburge The metadata fields should show up in this form?

![cal-form](https://user-images.githubusercontent.com/46832636/199768135-c49a4125-1527-4dab-a02e-af4dc54eda37.jpg)

**Comment by stevejburge** [comment]
@olatechpro Yes, please
