### ISSUE TITLE
Editorial Comments Reply

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Planner#945]
I can confirm this bug if the user is not the original commenter:

https://wordpress.org/support/topic/editorial-comments-reply/

> I currently have an editorial comment notification e-mail that works correctly, with the exception that when somebody replies/adds an editorial comment, that comment doesn’t get included in the body of the e-mail:
> 
> I have the following fields in the body of the e-mail:
> 
> Hi [psppno_receiver name],
> 
> [psppno_post title]
> [psppno_post permalink]
> 
> Comment
> [psppno_edcomment content]
> 
> The [psppno_edcomment content] field doesn’t display the comment content in the body of the e-mail if another user replies or adds a comment. The e-mail is received to notify that another user added a comment, but the actual comment doesn’t get displayed in the e-mail.
> 
> Is there a way to ensure that the replies to editorial comments get included in the body of the e-mail?
> 
> Thanks.

**Comment by olatechpro** [comment]
@stevejburge can you try and confirm this again and provide me with full details on how to test?

Currently, here's how i'm testing:
1. User 1 add editorial comment from post edit screen > All email received with new comment text
2. User 2 clicked Reply on the user 1 comment and add their own comment > All email received.

So, i'm not able to recreate this issue.

**Comment by stevejburge** [comment]
@BasketballBuzz We believe this was fixed in a recent release. Please let us know if you still see this

**Comment by BasketballBuzz** [comment]
@stevejburge @olatechpro still unable to receive the reply comment(s) in the body of the email.

Again, what we are trying to achieve here, is to ensure that "reply/replies comment(s)" get included in the body of the email notification. 

Currently, the only way to see/read any of the "comment replies" is to go back to the post and read the comment thread inside the WordPress post. This requires an editor to log in to the website and go into "edit mode" just to read the comments.

It would be ideal, if the "reply notifications email" included the actual comment in the body of the email 

1. Editor edits post and adds comment for changes etc.
2. Post author receives a notification email with the "actual comments" included in the body of the email if 
[psppno_edcomment content] is used.
3. The author logs back into the post, makes changes and adds a reply comment back to the editor to say all changes are complete etc.
4. Editor receives a notification email to notify that the author added a comment, BUT the actually "contents of the comment" [psppno_edcomment content] DON'T get included in the notification e-mail.
